src/carts/urls.py
from django.urls import path
from products.views import (ProductSlugDetailsView )
from carts.views import cart_home , cart_update,checkout_home,checkout_done_view


urlpatterns = [

    path("",cart_home , name="home"),
    path("update/",cart_update , name="update"),
    path("checkout/",checkout_home , name="checkout"),
    path('checkout/success/', checkout_done_view, name='success'),



]

src/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from . views import home_page,contact_page
from django.conf import settings
from django.conf.urls.static import static
# from products.views import (ProductListView,product_list_view,ProductDetailsView,product_details_view,
#                             ProductFeatureListView,ProductFeatureDetailsView,ProductSlugDetailsView )

from accounts.views import login_page,register_page,guest_register_view

from addresses.views import checkout_address_create_view,checkout_address_reuse_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , home_page , name="home"),
    path("contact/",contact_page, name="contact"),
    path("login/",login_page,name="login"),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path("register/",register_page , name="register"),
    # path("products/",ProductListView.as_view()),
    # path("products/<int:id>/",ProductDetailsView.as_view()),
    # path("feature/",ProductFeatureListView.as_view()),
    # path("feature/<int:pk>/",ProductFeatureDetailsView.as_view()),
    # path("productslug/<slug:slug>/",ProductSlugDetailsView.as_view())
    path("products/" , include(("products.urls" , 'products'), namespace="products") ),
    path("search/" , include(("search.urls" , 'search'), namespace="search") ),
    path("cart/" , include(("carts.urls" , 'carts'), namespace="cart") )
    


]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from products.views import (ProductListView,product_list_view,ProductDetailsView,product_details_view,
                            ProductFeatureListView,ProductFeatureDetailsView,ProductSlugDetailsView )


urlpatterns = [

    path("",ProductListView.as_view() , name="list"),
    # path("products/<int:id>/",ProductDetailsView.as_view()),
    # path("feature/",ProductFeatureListView.as_view()),
    # path("feature/<int:pk>/",ProductFeatureDetailsView.as_view()),
    path("<slug:slug>/",ProductSlugDetailsView.as_view() , name="detail")


]

src/templates/base/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" ></link>

src/templates/base/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{%  url 'home' as home_url %}
{%  url 'contact' as contact_url %}
{%  url 'products:list' as product_list_url %}
{%  url 'login' as login_url %}
{%  url 'register' as register_url %}
{%  url 'cart:home' as cart_url %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">{% if brand_name %} {{ brand_name }} {% else  %} CFE eCommerce {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %} active {% endif %}">
          <a class="nav-link"  href="{{ home_url }}" >Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item {% if request.path == product_list_url %} active {% endif %}">
          <a class="nav-link"  href="{{ product_list_url }}" >Product <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
          <a class="nav-link"  href="{{ contact_url }}" >Contact <span class="sr-only">(current)</span></a>
        </li>

        {%  if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link"  href="{{ login_url }}" >Logout <span class="sr-only">(current)</span></a>
        </li>
       {% else  %}
       <li class="nav-item {% if request.path == register_url %} active {% endif %}">
        <a class="nav-link"  href="{{ register_url }}" >Register <span class="sr-only">(current)</span></a>
      </li
       <li class="nav-item {% if request.path == login_url %} active {% endif %}">
        <a class="nav-link"  href="{{ login_url }}" >Login <span class="sr-only">(current)</span></a>
      </li>
       {% endif %}
       <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
        <a class="nav-link"  href="{{ cart_url }}" > {{  request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"> </i>  </a>
      </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>